# WIDDX Installer — adds `widdx` command to your system PATH AND installs dependencies
# Run: powershell -ExecutionPolicy Bypass -File install.ps1

$ProjectDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$BinDir = "$env:USERPROFILE\.widdx\bin"
$TargetBat = Join-Path $BinDir "widdx.bat"

# Create bin directory
New-Item -ItemType Directory -Force -Path $BinDir | Out-Null

# Function to find Python
function Find-Python {
    $commands = @("py", "python", "python3")
    foreach ($cmd in $commands) {
        try {
            $version = & $cmd --version 2>&1
            if ($LASTEXITCODE -eq 0) {
                return $cmd
            }
        } catch {}
    }
    return $null
}

# Step 1: Install dependencies
Write-Host "📦 Installing WIDDX dependencies..." -ForegroundColor Cyan
$pythonCmd = Find-Python
if (-not $pythonCmd) {
    Write-Host "❌ Error: Python not found! Install Python 3.10+ from python.org" -ForegroundColor Red
    pause
    exit 1
}

# Try installing using requirements.txt or pyproject.toml
$requirementsPath = Join-Path $ProjectDir "requirements.txt"
if (Test-Path $requirementsPath) {
    Write-Host "Installing from requirements.txt..." -ForegroundColor Cyan
    & $pythonCmd -m pip install -r $requirementsPath
    if ($LASTEXITCODE -ne 0) {
        Write-Host "⚠️ Warning: Failed to install some dependencies, trying 'pip install .'..." -ForegroundColor Yellow
        & $pythonCmd -m pip install -e $ProjectDir
    }
} else {
    Write-Host "Installing from pyproject.toml (editable mode)..." -ForegroundColor Cyan
    & $pythonCmd -m pip install -e $ProjectDir
}

# Step 2: Generate a launcher that auto-detects Python at runtime
Write-Host "🚀 Creating WIDDX launcher..." -ForegroundColor Cyan
$LauncherContent = @'
@echo off
REM WIDDX Launcher — auto-generated by install.ps1 (auto-detects Python)

where py >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    py "PROJECT_DIR\main.py" %*
    exit /b %ERRORLEVEL%
)

where python >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    python "PROJECT_DIR\main.py" %*
    exit /b %ERRORLEVEL%
)

where python3 >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    python3 "PROJECT_DIR\main.py" %*
    exit /b %ERRORLEVEL%
)

echo Error: Python not found. Install Python 3.10+ from python.org
pause
'@ -replace 'PROJECT_DIR', $ProjectDir
$LauncherContent | Out-File -FilePath $TargetBat -Encoding ASCII -Force

# Step 3: Add to user PATH if not already there
Write-Host "🔗 Adding WIDDX to your PATH..." -ForegroundColor Cyan
$CurrentPath = [Environment]::GetEnvironmentVariable("PATH", "User")
if ($CurrentPath -notlike "*$BinDir*") {
    $NewPath = "$CurrentPath;$BinDir"
    [Environment]::SetEnvironmentVariable("PATH", $NewPath, "User")
    # Also update current session
    $env:PATH = "$env:PATH;$BinDir"
    Write-Host "✅ Added $BinDir to your PATH" -ForegroundColor Green
} else {
    Write-Host "✅ $BinDir already in PATH" -ForegroundColor Green
}

Write-Host ""
Write-Host "🎉 WIDDX installed successfully!" -ForegroundColor Green
Write-Host "You can now type 'widdx' from ANY folder to launch it."
Write-Host ""
Write-Host "Usage:"
Write-Host "  widdx              Launch WIDDX in current directory"
Write-Host "  cd E:\projects      Go to your target folder"
Write-Host "  widdx              Projects will be saved in E:\projects\"
Write-Host ""
Write-Host "To uninstall, run: .\uninstall.ps1"
