# WIDDX Installer — adds `widdx` command to your system PATH
# Run: powershell -ExecutionPolicy Bypass -File install.ps1

$ProjectDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$BinDir = "$env:USERPROFILE\.widdx\bin"
$TargetBat = Join-Path $BinDir "widdx.bat"

# Create bin directory
New-Item -ItemType Directory -Force -Path $BinDir | Out-Null

# Generate a launcher that auto-detects Python at runtime
$LauncherContent = @'
@echo off
REM WIDDX Launcher — auto-generated by install.ps1 (auto-detects Python)

where py >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    py "PROJECT_DIR\main.py" %*
    exit /b %ERRORLEVEL%
)

where python >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    python "PROJECT_DIR\main.py" %*
    exit /b %ERRORLEVEL%
)

where python3 >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    python3 "PROJECT_DIR\main.py" %*
    exit /b %ERRORLEVEL%
)

echo Error: Python not found. Install Python 3.10+ from python.org
pause
'@ -replace 'PROJECT_DIR', $ProjectDir
$LauncherContent | Out-File -FilePath $TargetBat -Encoding ASCII -Force

# Add to user PATH if not already there
$CurrentPath = [Environment]::GetEnvironmentVariable("PATH", "User")
if ($CurrentPath -notlike "*$BinDir*") {
    $NewPath = "$CurrentPath;$BinDir"
    [Environment]::SetEnvironmentVariable("PATH", $NewPath, "User")
    # Also update current session
    $env:PATH = "$env:PATH;$BinDir"
    Write-Host "✅ Added $BinDir to your PATH" -ForegroundColor Green
} else {
    Write-Host "✅ $BinDir already in PATH" -ForegroundColor Green
}

Write-Host ""
Write-Host "🎉 WIDDX installed successfully!" -ForegroundColor Green
Write-Host "You can now type 'widdx' from ANY folder to launch it."
Write-Host ""
Write-Host "Usage:"
Write-Host "  widdx              Launch WIDDX in current directory"
Write-Host "  cd E:\projects      Go to your target folder"
Write-Host "  widdx              Projects will be saved in E:\projects\"
Write-Host ""
Write-Host "To uninstall, run: .\uninstall.ps1"
